version: 2.1
# To use browsers on CircleCI, uncomment the lines below and add steps to install them.
# For example, add these to `jobs.build.steps`:
# - browser-tools/install-chrome
# - browser-tools/install-chromedriver
# orbs:
#   browser-tools: circleci/browser-tools@1.2.3
jobs:
  build:
    working_directory: ~/drupal-skeleton
    docker:
      - image: cimg/php:8.3-browsers
      - image: cimg/mysql:8.0
        command: --max_allowed_packet=16M
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: circle_test

    environment:
      - PALANTIR_ENVIRONMENT: circleci
      - DRUPAL_ROOT: docroot
      - NODE_VERSION: 20

    steps:
      - run:
          name: Install packages
          command: |
            sudo apt-get update && sudo apt-get install -y libpng-dev default-mysql-client
      - run:
          name: Install nvm
          command: |
            set +e
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
            touch $BASH_ENV
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run:
          name: Configure PHP
          command: |
            echo "sendmail_path=/bin/true" | sudo tee -a "/etc/php.d/circleci.ini"
      - run:
          name: Update Composer
          command: |
            sudo composer self-update
      - run:
          name: Create artifacts directory
          command: mkdir /tmp/artifacts
      - run:
          name: Configure URL in /etc/hosts
          command: echo 127.0.0.1 ${CIRCLE_PROJECT_REPONAME}.local | sudo tee -a /etc/hosts

      # Package cache
      - restore_cache:
          keys:
            - package-cache-v1-

      # Source cache
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}
            - source-v1-

      - checkout
      - run:
          name: Composer install
          command: composer install --no-interaction --prefer-dist
      - run:
          name: Yarn install
          command: yarn install

      # Package cache. This is updated when the contents of the ~/.cache directory change.
      # Both Composer and Yarn use this directory.
      - run: ls -1R ~/.cache/ > /tmp/package-cache.txt
      - save_cache:
          key: package-cache-v1-{{ checksum "/tmp/package-cache.txt" }}
          paths:
              - ~/.cache

      # Source cache. This is updated for each different branch.
      - save_cache:
          key: source-v1-{{ .Branch }}
          paths:
            - ".git"

      - store_artifacts:
          path: /tmp/artifacts
      - store_test_results:
          path: /tmp/artifacts

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
                - /.*(readme|documentation).*/
